### ISSUE TITLE
Exception: Login failed. Check your credentials.

### ISSUE THREAD

**Issue by hyedalian2** [NelsonDane/auto-rsa#203]
I'm not sure what I am doing wrong, can someone guide me please.

I'm running the bot in a docker and running the command on discord.

I've tried with schwab, robinhood, firstrade and fidelity.

I am adding my credentials in the .env file

schwab=username:password:TTOP
robinhood=username:password:TTOP
firstrade=username:password:pin
fidelity=username:password

what am I missing? is there something I need to do on the bank's end to get it to work?

**Comment by NelsonDane** [comment]
First of all, all of those are supposed to be capitalized (`SCHWAB=` etc). Also, please share logs or something otherwise no one can really help

**Comment by hyedalian2** [comment]
sorry, they are capitalized.

Let's focus on firstrade now and we'll go from there, this is the log I get in my docker container when I run - !rsa buy 1 AAPL firstrade true - in the discord channel.

2024-03-22 12:36:43 auto-rsa    | Logging in to Firstrade...
2024-03-22 12:36:44 auto-rsa    | Error logging in to Firstrade: Login failed. Check your credentials.
2024-03-22 12:36:44 auto-rsa    | Traceback (most recent call last):
2024-03-22 12:36:44 auto-rsa    |   File "/app/firstradeAPI.py", line 36, in firstrade_init
2024-03-22 12:36:44 auto-rsa    |     firstrade = ft_account.FTSession(
2024-03-22 12:36:44 auto-rsa    |   File "/usr/local/lib/python3.10/dist-packages/firstrade/account.py", line 30, in __init__
2024-03-22 12:36:44 auto-rsa    |     self.login()
2024-03-22 12:36:44 auto-rsa    |   File "/usr/local/lib/python3.10/dist-packages/firstrade/account.py", line 80, in login
2024-03-22 12:36:44 auto-rsa    |     raise Exception("Login failed. Check your credentials.")
2024-03-22 12:36:44 auto-rsa    | Exception: Login failed. Check your credentials.
2024-03-22 12:36:44 auto-rsa    | 
2024-03-22 12:36:44 auto-rsa    | Error: firstrade not logged in, skipping...
2024-03-22 12:36:44 auto-rsa    | Error: firstrade not logged in, skipping...


for the .env file I am following as it is in the template, just filling in the info


## DISCORD BOT SETTINGS
# Discord Bot Token
DISCORD_TOKEN=Token (filled)
# Channel ID that the bot will run in
DISCORD_CHANNEL=ChannelID (filled)

## OPTIONAL SETTINGS
# Whether or not the bot should update automatically
ENABLE_AUTO_UPDATE="true"
# USE AT YOUR OWN RISK: Wether the bot should wait for a confirmation before executing trades in the CLI
DANGER_MODE="false"

## BROKER SETTINGS
# ALL BROKERS: Separate multiple accounts with different credentials
# at the same brokerage with a comma, then separate account credentials with a colon
# BROKER=BROKER_USERNAME:BROKER_PASSWORD,OTHER_BROKER_USERNAME:OTHER_BROKER_PASSWORD

# Fidelity
# FIDELITY=FIDELITY_USERNAME:FIDELITY_PASSWORD
FIDELITY=username:password (filled)

# Firstrade
# FIRSTRADE=FIRSTRADE_USERNAME:FIRSTRADE_PASSWORD:FIRSTRADE_PIN
FIRSTRADE=username:password:PIN# (filled)

# Robinhood
# If 2fa is enabled:
# ROBINHOOD=ROBINHOOD_USERNAME:ROBINHOOD_PASSWORD:ROBINHOOD_TOTP
# If 2fa is not enabled:
# ROBINHOOD=ROBINHOOD_USERNAME:ROBINHOOD_PASSWORD:NA
ROBINHOOD=username:password:TOTP (filled)

# Schwab
# If 2fa is enabled
# SCHWAB=SCHWAB_USERNAME:SCHWAB_PASSWORD:SCHWAB_TOTP_SECRET
# If 2fa is not enabled
# SCHWAB=SCHWAB_USERNAME:SCHWAB_PASSWORD:NA
SCHWAB=username:password:TOTP (filled)

# Tradier
# TRADIER=TRADIER_ACCESS_TOKEN
TRADIER=

# Tastytrade
# TASTYTRADE=TASTYTRADE_USERNAME:TASTYTRADE_PASSWORD
TASTYTRADE=

# Webull
# WEBULL=WEBULL_USERNAME:WEBULL_PASSWORD:WEBULL_DID:WEBULL_TRADING_PIN
WEBULL=

**Comment by thefnproblem** [comment]
Errors when using Fidelity,  Confirmed the account information is correct.  Log below

#7 0x55ccbe0917c4 <unknown>                                                      
#8 0x55ccbe07a7f3 <unknown>                                                      
#9 0x55ccbe04fea3 <unknown>                                                      
#10 0x55ccbe051255 <unknown>                                                     
#11 0x55ccbe2d81b0 <unknown>                                                     
#12 0x55ccbe2eaacf <unknown>                                                     
#13 0x55ccbe2ea510 <unknown>                                                     
#14 0x55ccbe2eb1e5 <unknown>                                                     
#15 0x55ccbe32f51a <unknown>                                                     
#16 0x55ccbe2eb524 <unknown>                                                     
#17 0x55ccbe2c9eae <unknown>                                                     
#18 0x55ccbe2f6768 <unknown>                                                     
#19 0x55ccbe2f6887 <unknown>                                                     
#20 0x55ccbe30fef0 <unknown>                                                     
#21 0x7f7060a6fac3 <unknown>                                                     
#22 0x7f7060b00a04 clone                                                         
                                                                                 
Traceback (most recent call last):                                               
  File "/app/fidelityAPI.py", line 188, in fidelity_account_info                 
    WebDriverWait(driver, 10).until(                                             
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/support/wait.p
y", line 105, in until                                                           
    raise TimeoutException(message, screen, stacktrace)                          
selenium.common.exceptions.TimeoutException: Message:  
#7 0x55ccbe0917c4 <unknown>                                                      
#8 0x55ccbe07a7f3 <unknown>                                                      
#9 0x55ccbe04fea3 <unknown>                                                      
#10 0x55ccbe051255 <unknown>                                                     
#11 0x55ccbe2d81b0 <unknown>                                                     
#12 0x55ccbe2eaacf <unknown>                                                     
#13 0x55ccbe2ea510 <unknown>                                                     
#14 0x55ccbe2eb1e5 <unknown>                                                     
#15 0x55ccbe32f51a <unknown>                                                     
#16 0x55ccbe2eb524 <unknown>                                                     
#17 0x55ccbe2c9eae <unknown>                                                     
#18 0x55ccbe2f6768 <unknown>                                                     
#19 0x55ccbe2f6887 <unknown>                                                     
#20 0x55ccbe30fef0 <unknown>                                                     
#21 0x7f7060a6fac3 <unknown>                                                     
#22 0x7f7060b00a04 clone                                                         
                                                                                 
                                                                                 
Fidelity Error: Fidelity 1: Error getting account info                           
Traceback (most recent call last):                                               
  File "/app/fidelityAPI.py", line 165, in fidelity_init                         
    raise Exception(f"{name}: Error getting account info")                       
Exception: Fidelity 1: Error getting account info                                
                                                                                 
Error: fidelity not logged in, skipping...                                       
Error: fidelity not logged in, skipping...

**Comment by hyedalian2** [comment]
just an update. I was able to get Robinhood and Schwab working. They were issues with my bank accounts. However Firstrade still doesn't work. This is the error I get.

`2024-03-28 14:29:12 auto-rsa    | Logging in to Firstrade...
2024-03-28 14:29:13 auto-rsa    | Error logging in to Firstrade: Login failed. Check your credentials.
2024-03-28 14:29:13 auto-rsa    | Traceback (most recent call last):
2024-03-28 14:29:13 auto-rsa    |   File "/app/firstradeAPI.py", line 36, in firstrade_init
2024-03-28 14:29:13 auto-rsa    |     firstrade = ft_account.FTSession(
2024-03-28 14:29:13 auto-rsa    |   File "/usr/local/lib/python3.10/dist-packages/firstrade/account.py", line 30, in __init__
2024-03-28 14:29:13 auto-rsa    |     self.login()
2024-03-28 14:29:13 auto-rsa    |   File "/usr/local/lib/python3.10/dist-packages/firstrade/account.py", line 80, in login
2024-03-28 14:29:13 auto-rsa    |     raise Exception("Login failed. Check your credentials.")
2024-03-28 14:29:13 auto-rsa    | Exception: Login failed. Check your credentials.
2024-03-28 14:29:13 auto-rsa    | 
2024-03-28 14:29:13 auto-rsa    | Error: firstrade not logged in, skipping...
2024-03-28 14:29:13 auto-rsa    | Error: firstrade not logged in, skipping...`

I know it says check your credentials but I am 100% correct that I am putting in the correct information.

I am following this format 

# Firstrade
# FIRSTRADE=FIRSTRADE_USERNAME:FIRSTRADE_PASSWORD:FIRSTRADE_PIN
FIRSTRADE=usersname:P@ssw0rd:4PIN

not sure what I am doing wrong, or if there's something I need to enable on the banks end.
