### ISSUE TITLE
Robinhood & Schwab not logged in, skipping (Chase and Vanguard not working)

### ISSUE THREAD

**Issue by Nohealz** [NelsonDane/auto-rsa#258]
I have many of them able to login and verify my holdings.

Robinhood tries to login but says non 32 bit digit found for 2fa. I tried without 2fa but when I enter the texted code nothing happens.

Schwab doesn't even attempt to login.

CHASE: Installed playwright. Starts to login, goes to text code screen and then nothing happens. It refreshes to login screen and the login screen refreshes every 30 seconds exactly.

VANGUARD: Attempts to start playwright but just errors out before it opens.

I'm happy to recreate and try things. Really looking forward to this running well.

**Comment by Nohealz** [comment]
Using Discord Bot Python script
Testing 1 at a time with '!rsa holdings "broker"

**Robinhood**
```
Logging in to Robinhood...
Error: Unable to log in to Robinhood: Non-base32 digit found

Error: robinhood not logged in, skipping...
```

**Schwab**: 2fa set to 'only on untrusted devices. So I have this set to NA in my `.env`. I double checked my username and password are correct.
```
Logging in to Schwab...
Error logging in to Schwab: Login was not successful; please check username and password
Traceback (most recent call last):
  File "C:\Users\chey2\anaconda3\Lib\site-packages\schwab_api\authentication.py", line 96, in _async_login
    await self.page.wait_for_url(re.compile(r"app/trade"), wait_until="domcontentloaded") # Making it more robust than specifying an exact url which may change.
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chey2\anaconda3\Lib\site-packages\playwright\async_api\_generated.py", line 8798, in wait_for_url
    await self._impl_obj.wait_for_url(
  File "C:\Users\chey2\anaconda3\Lib\site-packages\playwright\_impl\_page.py", line 543, in wait_for_url
    return await self._main_frame.wait_for_url(**locals_to_params(locals()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chey2\anaconda3\Lib\site-packages\playwright\_impl\_frame.py", line 233, in wait_for_url
    async with self.expect_navigation(
  File "C:\Users\chey2\anaconda3\Lib\site-packages\playwright\_impl\_event_context_manager.py", line 33, in __aexit__
    await self._future
  File "C:\Users\chey2\anaconda3\Lib\site-packages\playwright\_impl\_frame.py", line 208, in continuation
    event = await waiter.result()
            ^^^^^^^^^^^^^^^^^^^^^
playwright._impl._errors.TimeoutError: Timeout 30000ms exceeded.

```

**Chase**: logs in, makes it to authenticator screen but then quickly goes back to empty login screen. When I close the browser....
```
Logging in to Chase...
Error logging in to Chase: Target page, context or browser has been closed
=========================== logs ===========================
waiting for request https://secure.chase.com/svc/rl/accounts/secure/v1…
============================================================
Traceback (most recent call last):
  File "C:\Users\chey2\auto-rsa\chaseAPI.py", line 85, in chase_init
    all_accounts = ch_account.AllAccount(ch_session)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chey2\anaconda3\Lib\site-packages\chase\account.py", line 38, in __init__
    self.all_account_info = self.get_all_account_info()
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chey2\anaconda3\Lib\site-packages\chase\account.py", line 53, in get_all_account_info
    invest_json = self.get_investment_json(urls[0])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chey2\anaconda3\Lib\site-packages\chase\account.py", line 103, in get_investment_json
    request = request_context.value
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chey2\anaconda3\Lib\site-packages\playwright\_impl\_sync_base.py", line 59, in value
    raise exception
playwright._impl._errors.Error: Target page, context or browser has been closed
=========================== logs ===========================
waiting for request https://secure.chase.com/svc/rl/accounts/secure/v1…
============================================================
```

**Vanguard**: got it to login finally after multiple runs. Here are the errors though.
```
Logging in to Vanguard...
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000220ACC1AA20>
Traceback (most recent call last):
  File "C:\Users\chey2\anaconda3\Lib\asyncio\proactor_events.py", line 116, in __del__
    _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chey2\anaconda3\Lib\asyncio\proactor_events.py", line 80, in __repr__
    info.append(f'fd={self._sock.fileno()}')
                      ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chey2\anaconda3\Lib\asyncio\windows_utils.py", line 102, in fileno
    raise ValueError("I/O operation on closed pipe")
ValueError: I/O operation on closed pipe
Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x00000220ACC19300>
Traceback (most recent call last):
  File "C:\Users\chey2\anaconda3\Lib\asyncio\base_subprocess.py", line 125, in __del__
    _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chey2\anaconda3\Lib\asyncio\base_subprocess.py", line 70, in __repr__
    info.append(f'stdin={stdin.pipe}')
                ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chey2\anaconda3\Lib\asyncio\proactor_events.py", line 80, in __repr__
    info.append(f'fd={self._sock.fileno()}')
                      ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chey2\anaconda3\Lib\asyncio\windows_utils.py", line 102, in fileno
    raise ValueError("I/O operation on closed pipe")
ValueError: I/O operation on closed pipe
Exception ignored in: <function StreamWriter.__del__ at 0x00000220ACC05F80>
Traceback (most recent call last):
  File "C:\Users\chey2\anaconda3\Lib\asyncio\streams.py", line 396, in __del__
    self.close()
  File "C:\Users\chey2\anaconda3\Lib\asyncio\streams.py", line 344, in close
    return self._transport.close()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chey2\anaconda3\Lib\asyncio\proactor_events.py", line 109, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\chey2\anaconda3\Lib\asyncio\base_events.py", line 761, in call_soon
    self._check_closed()
  File "C:\Users\chey2\anaconda3\Lib\asyncio\base_events.py", line 519, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000220ACC1AA20>
Traceback (most recent call last):
  File "C:\Users\chey2\anaconda3\Lib\asyncio\proactor_events.py", line 116, in __del__
    _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chey2\anaconda3\Lib\asyncio\proactor_events.py", line 80, in __repr__
    info.append(f'fd={self._sock.fileno()}')
                      ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chey2\anaconda3\Lib\asyncio\windows_utils.py", line 102, in fileno
    raise ValueError("I/O operation on closed pipe")
ValueError: I/O operation on closed pipe
Logged in to Vanguard!
The following Vanguard accounts were found: ['xxxxxxxx', 'xxxxxxxx']
==============================
VANGUARD Holdings
==============================
Vanguard 1 (xxxxxxxx)
correct stuff

Total: $xxx

Vanguard 1 (xxxxxxxx)
correct stuff

Total: $xxx

==============================
```

**Comment by NelsonDane** [comment]
I'm glad that you got RH working, one less thing for me to worry about 😅 

For Schwab, I'm pretty sure other people have had errors when setting 2FA to `NA`. There's probably a bug somewhere that I haven't had time to track down yet :( . Everyone reports that setting 2FA up solved the issue, and while that probably isn't ideal it's the best I have for now.

Both Chase and Vanguard have a `DEBUG` option in the `.env` (check their sections of the README), that could provide more info or a more detailed stack trace.

**Comment by MaxxRK** [comment]
Hello!

I wrote both the chase and vanguard api's.
I would say we try to get chase fixed first. Do you mind posting a screenshot of what screen that chase is getting stuck on?
Another user has given me a trace of a screen that I have not seen yet in the login process. I should be able to get a fix in for that in the next week. If you post a screenshot I should be able to see if it is the same issue.

**Comment by MaxxRK** [comment]
I have updated the `chaseinvest-api` please make sure auto-rsa is updated and give it a try. If it still errors, please send me a screenshot.

**Comment by Nohealz** [comment]
> I have updated the `chaseinvest-api` please make sure auto-rsa is updated and give it a try. If it still errors, please send me a screenshot.

I updated and verified I have the updated version. It did make it 1 screen further.
0.1.6 only made it as far as the screen after the login. This was the screen that had you pick how to be sent a security code.
0.1.7 does select the texting option. Next screen verifies my number. After about 5 seconds it refreshes back to login screen. 
![Chase](https://github.com/NelsonDane/auto-rsa/assets/104795615/5a0c0981-c049-46cf-a6bb-e591bee3d34e)

I've tried to game it by manually hitting next, it texts me, and I can get the code entered and hit enter but it isn't quite fast enough before it refreshes back to login.

I did do a debug on it so if you need to see any files let me know.

**Comment by Nohealz** [comment]
> I'm glad that you got RH working, one less thing for me to worry about 😅
> 
> For Schwab, I'm pretty sure other people have had errors when setting 2FA to `NA`. There's probably a bug somewhere that I haven't had time to track down yet :( . Everyone reports that setting 2FA up solved the issue, and while that probably isn't ideal it's the best I have for now.
> 
> Both Chase and Vanguard have a `DEBUG` option in the `.env` (check their sections of the README), that could provide more info or a more detailed stack trace.

I went through the Schwab 2fa steps, login failed 1st attempt giving me the same incorrect username or password issue. 2nd attempt it logged in just fine. I tested it and it was able to sell what I needed but there were some errors to it. Keeping the acc numbers in so you can follow. Couple account specifics to mention.

- '0267' is an HSA that does not have ToS enabled and it worked eventually. The others are all in ToS.
- '6573' is a managed account and I do not have direct access to trade in. Is there a way I can disable this account?

```
Schwab 1 selling 1.0 STRR @ market
unsuccessful, retrying...
retry unsuccessful
Schwab 1 account xxxx6573: The order verification produced the following messages: ['This order cannot be accepted because the number of shares of %SYMBOL% you are attempting to sell with this and other open orders is greater than the %1% shares held in this account.  (AC1122)']
Schwab 1 account xxxx4846: The order verification was successful
unsuccessful, retrying...
Schwab 1 account xxxx0267: The order verification was retry successful
Schwab 1 account xxxx0267: The order verification produced the following messages: ['Please note that the issuer of this security is deficient in meeting the Exchange\x92s continued listing requirements. You may want to consider doing further research before placing this order.  (DO840)', 'This account currently holds %1% shares of %SYMBOL%.  (AC109)']
Schwab 1 account xxxx1340: The order verification was successful
Schwab 1 account xxxx7116: The order verification was successful
Schwab 1 selling 1.0 WKHS @ market
unsuccessful, retrying...
retry unsuccessful
Schwab 1 account xxxx6573: The order verification produced the following messages: ['This order cannot be accepted because the number of shares of %SYMBOL% you are attempting to sell with this and other open orders is greater than the %1% shares held in this account.  (AC1122)']
Schwab 1 account xxxx4846: The order verification was successful
unsuccessful, retrying...
Schwab 1 account xxxx0267: The order verification was retry successful
Schwab 1 account xxxx0267: The order verification produced the following messages: ['Please note that the issuer of this security is deficient in meeting the Exchange\x92s continued listing requirements. You may want to consider doing further research before placing this order.  (DO840)', 'This account currently holds %1% shares of %SYMBOL%.  (AC109)']
Schwab 1 account xxxx1340: The order verification was successful
Schwab 1 account xxxx7116: The order verification was successful
All Schwab transactions complete
```

**Comment by MaxxRK** [comment]
I have pushed an update to chase `v0.1.8` Please send me a message on Discord if you have it.  My username is `maxxrk`. I do not want to continue to push small updates to try and get this fixed one step at a time. I will send you a test script to run. That way we can just update auto-rsa once to finish the fix.

**Comment by Nohealz** [comment]
> maxxrk

I have it installed, same progress as before. I sent you a discord invite, similar to my name here.
```
Name: chaseinvest-api
Version: 0.1.8
Summary: An unofficial API for Chase Invest
Home-page: https://github.com/MaxxRK/chaseinvest-api
Author: MaxxRK
Author-email: maxxrk@pm.me
License: MIT
Location: C:\Users\chey2\anaconda3\Lib\site-packages
Requires: playwright, playwright-stealth
Required-by:
```

**Comment by Nohealz** [comment]
@MaxxRK Thank you for helping out with adding the functionality to go through Chase login a different way than you do.

The only issue that was not figured out but was able to be corrected is a popup after login. When that was manually cleared it was never seen again. For anyone that stumbles across this is how to clear it manually.

1. Enable debug in your `.env` file. This will create a `.zip` file inside 'auto-rsa' directory.
2. Dry run `!rsa buy 1 AAPL chase true`
3. Navigate to auto-rsa folder and `playwright show-trace nameoftrace.zip`
4. Run `playwright ff` and manually do exactly what the trace playback does.
5. When you get to the popup, press the 'x'. It shouldn't pop up for you anymore.
6. Do another dry run and make sure everything is operational.

The other 3 brokers that began this thread are all working as well. Vanguard unfortunately looks to be not allowing RSA trades.
