### ISSUE TITLE
Tastytrade trading

### ISSUE THREAD

**Issue by Sabermoose19** [NelsonDane/auto-rsa#89]
`Tastytrade 1: buying 1 of AAL
Traceback (most recent call last):
  File "/home/saber/rsa_bot/auto-rsa/autoRSA.py", line 82, in fun_run
    globals()[fun_name](
  File "/home/saber/rsa_bot/auto-rsa/tastyAPI.py", line 301, in tastytrade_transaction
    asyncio.run(
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/saber/rsa_bot/auto-rsa/tastyAPI.py", line 149, in tastytrade_execute
    day_trade_ok = day_trade_check(obj, acct, cash_balance)
  File "/home/saber/rsa_bot/auto-rsa/tastyAPI.py", line 27, in day_trade_check
    trading_status = acct.get_trading_status(tt)
  File "/home/saber/.local/lib/python3.10/site-packages/tastytrade/account.py", line 455, in get_trading_status
    return TradingStatus(**data)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for TradingStatus
enhanced-fraud-safeguards-enabled-at
  field required (type=value_error.missing)

Error in tastytrade_transaction with tastytrade: 1 validation error for TradingStatus
enhanced-fraud-safeguards-enabled-at
  field required (type=value_error.missing)
Self:
                 Action: buy
                 Amount: 1
                 Stock: ['AAL']
                 Time: day
                 Price: market
                 Brokers: ['tastytrade']
                 Not Brokers: []
                 Dry: False
                 Holdings: False
                 Logged In: [<helperAPI.Brokerage object at 0x7f4402d7bee0>]`

This is the error that I get when I try to execute a trade with tastytrade

**Comment by NelsonDane** [comment]
Thanks for reaching out @Sabermoose19! This is a bug in the Tastytrade API, @MaxxRK figured out what was wrong and submitted a PR (https://github.com/tastyware/tastytrade/pull/90). In the meantime, we've disabled the test that was causing failure, so if you pull the latest changes it should run with the temporary fix =)
